"use strict";

const bodyParser = require("body-parser");
const express = require("express");
const logger = require("winston");
const { routesHandlers: routesHandlersBlogPost } = require("./blog-post");
const { routesHandlers: routesHandlersComment } = require("./comment");

const routerWeb = express.Router();
const routerApi = express.Router();

// --------------------------------------------------
// Web
// --------------------------------------------------
/**
 * This route is only used for the Demo application deployed
 * to clean-up the BlogPost generated by the users.
 * It is executed every 24h by a cron job.
 */
routerWeb.get(
    "/clean-up",
    (req, res, next) => {
        // Validate if it is the Cron service
        const ipAppEngine =
            req.headers["x-forwarded-for"] &&
            req.headers["x-forwarded-for"].indexOf("0.1.0.1") >= 0;

        const cronHeader = !!req.headers["x-appengine-cron"];

        if (!cronHeader || !ipAppEngine) {
            logger.warn(
                `The unauthorized host ${req.ip} tried to clean up BlogPost`
            );
            return res.status(403).send("Not allowed");
        }
        next();
    },
    routesHandlersBlogPost.cleanUp
);
routerWeb.get("/", routesHandlersBlogPost.index);
routerWeb.get("/:id", routesHandlersBlogPost.detail);

// --------------------------------------------------
// REST API
// --------------------------------------------------
routerApi.delete("/blog/:id", routesHandlersBlogPost.deletePost);
routerApi.get("/blog/:id/comments", routesHandlersComment.getComments);
routerApi.post(
    "/blog/:id/comments",
    bodyParser.json(),
    routesHandlersComment.createComment
);
routerApi.delete("/comments/:id", routesHandlersComment.deleteComment);

module.exports = {
    web: routerWeb,
    api: routerApi
};
